## 1. Diccionarios

Un diccionario es una estructura de datos que te permite almacenar y organizar datos en forma de pares llave-valor.

1. Pares llave-valor: Cada elemento en un diccionario tiene una llave única que se asocia con un valor. Las llaves pueden ser cadenas de texto, números, booleanos o incluso otros diccionarios. Los valores pueden ser cualquier tipo de dato en Python.
2. Acceso rápido: Los diccionarios son muy eficientes para acceder a datos por su llave. Puedes usar la sintaxis **diccionario[llave]** para obtener el valor asociado a una llave específica.
3. Modificables: Puedes agregar, eliminar o modificar elementos en un diccionario de forma dinámica.
4. No ordenados: Los diccionarios no son ordenados por defecto.

In [20]:
#diccionario vacio
mi_diccionario ={}

#diccionario con valores
mi_diccionario={"nombre": "Diego", 
                "edad": 32, 
                "pais": "Guatemala", 
                "Casado": True}

mi_diccionario

{'nombre': 'Diego', 'edad': 32, 'pais': 'Guatemala', 'Casado': True}

In [12]:
diccionario = {"nombre": "Diego",
               "carnet": 11006956,
               "fecha_nacimiento": '12/12/1992',
               "programa": "PAPD",
               "notas": {
                   "CDP": 90,
                   "EAI": 95,
                   "DCDW": 98
                   }
              }
diccionario

{'nombre': 'Diego',
 'carnet': 11006956,
 'fecha_nacimiento': '12/12/1992',
 'programa': 'PAPD',
 'notas': {'CDP': 90, 'EAI': 95, 'DCDW': 98}}

In [13]:
lista = [1, 2, 3, 5, 6]
lista

[1, 2, 3, 5, 6]

*Las listas en R son equivalentes a las diccionarios en Python

*Los arreglos/colecciones son equivalentes a listas en Python

In [14]:
#otra forma de diccion
metricas_modelos= dict(SVM = 0.957, ANN = 0.879, KNN = 0.958)
metricas_modelos

{'SVM': 0.957, 'ANN': 0.879, 'KNN': 0.958}

In [21]:
mi_diccionario

{'nombre': 'Diego', 'edad': 32, 'pais': 'Guatemala', 'Casado': True}

In [22]:
mi_diccionario["nombre"]

'Diego'

In [23]:
diccionario[0]

KeyError: 0

In [24]:
diccionario

{'nombre': 'Diego',
 'carnet': 11006956,
 'fecha_nacimiento': '12/12/1992',
 'programa': 'PAPD',
 'notas': {'CDP': 90, 'EAI': 95, 'DCDW': 98}}

In [27]:
diccionario["notas"]["DCDW"]

98

In [29]:
diccionario['seccion']= "A"

In [30]:
diccionario

{'nombre': 'Diego',
 'carnet': 11006956,
 'fecha_nacimiento': '12/12/1992',
 'programa': 'PAPD',
 'notas': {'CDP': 90, 'EAI': 95, 'DCDW': 98},
 'seccion': 'A'}

In [31]:
diccionario["notas"]["IIC"] = 98

In [32]:
diccionario

{'nombre': 'Diego',
 'carnet': 11006956,
 'fecha_nacimiento': '12/12/1992',
 'programa': 'PAPD',
 'notas': {'CDP': 90, 'EAI': 95, 'DCDW': 98, 'IIC': 98},
 'seccion': 'A'}

# Operaciones

In [34]:
#eliminar elementos
del diccionario["seccion"]
diccionario

{'nombre': 'Diego',
 'carnet': 11006956,
 'fecha_nacimiento': '12/12/1992',
 'programa': 'PAPD',
 'notas': {'CDP': 90, 'EAI': 95, 'DCDW': 98, 'IIC': 98}}

In [35]:
#cantidad de elementos
len(diccionario)

5

In [36]:
#extraemos solo las llaves
list(diccionario.keys())

['nombre', 'carnet', 'fecha_nacimiento', 'programa', 'notas']

In [38]:
#extraer solo los valores
list(diccionario.values())

['Diego',
 11006956,
 '12/12/1992',
 'PAPD',
 {'CDP': 90, 'EAI': 95, 'DCDW': 98, 'IIC': 98}]

In [39]:
#devuelve una lista de pares llave-valor
list(diccionario.items())

[('nombre', 'Diego'),
 ('carnet', 11006956),
 ('fecha_nacimiento', '12/12/1992'),
 ('programa', 'PAPD'),
 ('notas', {'CDP': 90, 'EAI': 95, 'DCDW': 98, 'IIC': 98})]

# Numpy

In [44]:
!conda install numpy --yes

Solving environment: ...working... done

# All requested packages already installed.





==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0




NumPy (abreviatura de Numerical Python) es una biblioteca de código abierto para el lenguaje de programación Python que se utiliza para la computación científica.

Es la base de muchas otras bibliotecas de Python para el análisis de datos, como Pandas, SciPy, Matplotlib, SciKit Learn, Tensorflow, OpenCV entre otras.

## Algunas Carracteristicas:

1. Arrays multidimensionales: NumPy ofrece una estructura de datos llamada ndarray que permite trabajar con arrays multidimensionales de forma eficiente.

2. Funciones matemáticas: NumPy incluye una amplia gama de funciones matemáticas para realizar operaciones con arrays, como suma, resta, multiplicación, división, cálculo de raíces cuadradas, etc.

3. Optimización: El código de NumPy está optimizado para ofrecer un alto rendimiento en operaciones con arrays.

In [45]:
import numpy as np #acortamos el nombre de la libreria.

In [46]:
#creamos arreglo de numpy
# tipos de datos = int, float, bool, str.
x= np.array([10, 20, 30, 40, 50, 60,], dtype="int")
x

array([10, 20, 30, 40, 50, 60])

In [49]:
#creamos un array en secucia de 1 a 20 con step
y = np.arange(1, 21, 1)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
#creamos un arreglo en secuencia de 0 a 10 generando 5 valores en el rango
el step seria 1/(max - min)+1)
z = np.linspace(0,11,5)
z

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [51]:
#creamos arraglos lleno de cero
x= np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
#creamos arraglos lleno de unos
x= np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
y= np.empty((5,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
z = np.random.randint(1,10,5)
z

array([3, 2, 6, 2, 6])

In [65]:
## para el proyecto
z= np.random.randint(65,90,7)
codigo =""
suma = 0
for i in z:
    numero = str(np.random.randint(0,9,1)[0])
    #suma = suma + numero
    codigo = codigo + numero + chr(i)
#if para los proximos numeros
print (codigo)

5G3W6B3L1I1P0P


# rangos y dimensiones

In [66]:
y = np.array([[10,20,30,40,50],[15,25,35,45,55]])
y

array([[10, 20, 30, 40, 50],
       [15, 25, 35, 45, 55]])

In [68]:
rango = y.ndim
dimension = y.shape
print (f"El tensor es de rango {rango} y dimensiones {dimension}")

El tensor es de rango 2 y dimensiones (2, 5)


In [69]:
y[1,3]

45

In [74]:
x = np.array([[[10,20,30,40,50], [33,44,55,66, 77]], [[111, 222,333,444, 555], [777,888, 999,232, 656]]])
x

array([[[ 10,  20,  30,  40,  50],
        [ 33,  44,  55,  66,  77]],

       [[111, 222, 333, 444, 555],
        [777, 888, 999, 232, 656]]])

In [75]:
x.ndim

3

In [76]:
x.shape

(2, 2, 5)

In [78]:
x[1,1,2]

999